mgr/stats: initialize mx_last_updated in FSPerfStats
Fixes the error in teuthology log:
AttributeError: 'FSPerfStats' object has no attribute 'mx_last_updated'

Fixes: https://tracker.ceph.com/issues/65073
Signed-off-by: Jos Collin <jcollin@redhat.com>
(cherry picked from commit b96ad6126110b292fca053fdfc6a956a6eb0f01e)
(cherry picked from commit 7042ab4aa778e1e4f3590d29abcf36e186917df4)

Resolves: rhbz#2280750