rgw: improved error when listing indexless bucket
without this change, ListObjects would attempt to list index shard
objects that don't exist and fail with:

> ERROR: S3 error: 404 (NoSuchKey)

after:

> ERROR: S3 error: 405 (MethodNotAllowed): Indexless buckets cannot be listed

Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit fa4c5cebd2b611c20b0fc9da122b138900cb571b)

Resolves: rhbz#2135354